### PR TITLE
Move format strings to progmem.

### PR DESCRIPTION
**Pull request by gsliepen**

### CODE REVIEW

**Review by renato-grottesi — APPROVED** [review]
The /**/ are there for clang-format :-p
I'll merge the change and put them back before returning the formatter :-)

**Comment by gsliepen** [comment]
Aah! I was thinking "why these useless comments that I have to manually reindent?" Can you put the clang-format command used for the codebase somewhere? Then I can run it before making a pull request next time.

**Comment by renato-grottesi** [comment]
I just run the last clang-format on ubuntu with parameters

**Comment by renato-grottesi** [comment]
with *no* parameters

**Pull request merged**
